remote_theme: just-the-docs/just-the-docs

title: macOS & Linux Guides
description: Practical guides for problems that are hard to find solutions for online.

url: "https://eliekh05.github.io"
baseurl: "/guides"

# Sidebar
nav_sort: case_insensitive

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Footer
footer_content: "macOS &amp; Linux Guides"

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/eliekh05/guides"
aux_links_new_tab: true

# Color scheme
color_scheme: dark

plugins:
  - jekyll-remote-theme
